#############################################################################
# Makefile for building: MutiCamApp
# Generated by qmake (3.1) (Qt 6.8.2)
# Project:  MutiCamApp.pro
# Template: app
# Command: D:\ProgramData\Qt\6.8.2\msvc2022_64\bin\qmake.exe -o Makefile MutiCamApp.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: debug
install: debug-install
uninstall: debug-uninstall
QMAKE         = D:\ProgramData\Qt\6.8.2\msvc2022_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = D:\ProgramData\Qt\6.8.2\msvc2022_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = D:\ProgramData\Qt\6.8.2\msvc2022_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = 
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		debug \
		release


debug: $(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: $(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: MutiCamApp.pro ..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\win32-msvc\qmake.conf ..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\spec_pre.prf \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\common\windows-desktop.conf \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\win32\windows_vulkan_sdk.prf \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\common\windows-vulkan.conf \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\common\msvc-desktop.conf \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\qconfig.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_ext_freetype.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_ext_libjpeg.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_ext_libpng.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_ext_openxr_loader.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3danimation.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3danimation_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dcore.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dcore_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dextras.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dextras_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dinput.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dinput_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dlogic.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dlogic_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dquick.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dquick_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dquickanimation.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dquickextras.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dquickinput.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dquickrender.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dquickscene2d.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dquickscene3d.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dquickscene3d_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3drender.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3drender_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_activeqt.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_activeqt_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_axbase_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_axcontainer.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_axcontainer_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_axserver.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_axserver_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_bluetooth.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_bluetooth_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_bodymovin_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_charts.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_charts_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_chartsqml.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_chartsqml_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_concurrent.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_concurrent_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_core.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_core5compat.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_core5compat_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_core_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_datavisualization.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_datavisualization_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_datavisualizationqml.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_datavisualizationqml_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_dbus.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_dbus_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_designer.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_designer_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_designercomponents_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_entrypoint_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_example_icons_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_examples_asset_downloader_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_fb_support_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_freetype_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_graphs.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_graphs_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_graphswidgets.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_graphswidgets_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_grpc.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_grpc_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_grpcquick.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_grpcquick_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_gui.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_gui_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_harfbuzz_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_help.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_help_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_httpserver.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_httpserver_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_jpeg_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_jsonrpc_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_labsanimation.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_labsanimation_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_labsfolderlistmodel.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_labsfolderlistmodel_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_labsplatform.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_labsplatform_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_labsqmlmodels.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_labsqmlmodels_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_labssettings.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_labssettings_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_labssharedimage.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_labssharedimage_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_labswavefrontmesh.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_labswavefrontmesh_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_languageserver_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_linguist.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_location.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_location_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_multimedia.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_multimedia_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_multimediaquick_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_multimediatestlibprivate_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_multimediawidgets.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_network.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_network_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_networkauth.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_networkauth_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_nfc.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_nfc_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_opengl.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_opengl_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_openglwidgets.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_openglwidgets_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_png_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_positioning.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_positioning_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_positioningquick.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_positioningquick_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_printsupport.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_printsupport_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_protobuf.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_protobuf_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_protobufqtcoretypes.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_protobufqtcoretypes_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_protobufqtguitypes.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_protobufqtguitypes_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_protobufquick.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_protobufquick_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_protobufwellknowntypes.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_protobufwellknowntypes_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qdoccatch_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qdoccatchconversions_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qdoccatchgenerators_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qml.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qml_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmlassetdownloader.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmlassetdownloader_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmlcompiler.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmlcompiler_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmlcore.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmlcore_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmldebug_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmldom_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmlintegration.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmlintegration_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmllocalstorage.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmllocalstorage_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmlls_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmlmeta.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmlmeta_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmlmodels.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmlmodels_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmlnetwork.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmlnetwork_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmltest.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmltest_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmltoolingsettings_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmltyperegistrar_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmlworkerscript.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmlworkerscript_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmlxmllistmodel.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmlxmllistmodel_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3d.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3d_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dassetimport.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dassetimport_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dassetutils.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dassetutils_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3deffects.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3deffects_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dglslparser_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dhelpers.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dhelpers_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dhelpersimpl.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dhelpersimpl_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3diblbaker.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3diblbaker_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dparticleeffects.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dparticleeffects_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dparticles.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dparticles_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dphysics.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dphysics_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dphysicshelpers.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dphysicshelpers_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3druntimerender.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3druntimerender_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dspatialaudio_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dutils.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dutils_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dxr.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dxr_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2basic.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2basic_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2basicstyleimpl.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2basicstyleimpl_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fusion.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fusion_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fusionstyleimpl.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2imagine.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2imagine_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2imaginestyleimpl.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2impl.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2impl_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2material.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2material_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2materialstyleimpl.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2materialstyleimpl_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2universal.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2universal_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2universalstyleimpl.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2universalstyleimpl_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2windowsstyleimpl.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2windowsstyleimpl_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrolstestutilsprivate_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2utils.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2utils_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickeffects_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quicklayouts.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quicklayouts_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickparticles_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickshapes_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quicktemplates2.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quicktestutilsprivate_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quicktimeline.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quicktimeline_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quicktimelineblendtrees.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quicktimelineblendtrees_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickvectorimage.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickvectorimage_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickvectorimagegenerator_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickwidgets.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_remoteobjects.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_remoteobjects_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_remoteobjectsqml.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_remoteobjectsqml_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_repparser.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_repparser_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_scxml.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_scxml_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_scxmlqml.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_scxmlqml_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_sensors.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_sensors_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_sensorsquick.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_sensorsquick_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_serialbus.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_serialbus_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_serialport.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_serialport_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_shadertools.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_shadertools_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_spatialaudio.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_spatialaudio_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_sql.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_sql_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_statemachine.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_statemachine_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_statemachineqml.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_statemachineqml_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_svg.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_svg_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_svgwidgets.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_svgwidgets_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_testlib.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_testlib_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_texttospeech.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_texttospeech_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_tools_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_uiplugin.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_uitools.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_uitools_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_virtualkeyboard.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_virtualkeyboard_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_virtualkeyboardsettings.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_virtualkeyboardsettings_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_webchannel.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_webchannel_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_webchannelquick.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_webchannelquick_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_websockets.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_websockets_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_webview.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_webview_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_webviewquick.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_webviewquick_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_widgets.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_widgets_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_xml.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_xml_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_zlib_private.pri \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\qt_functions.prf \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\qt_config.prf \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\win32-msvc\qmake.conf \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\spec_post.prf \
		.qmake.stash \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\exclusive_builds.prf \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\common\msvc-version.conf \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\toolchain.prf \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\default_pre.prf \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\win32\default_pre.prf \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\resolve_config.prf \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\exclusive_builds_post.prf \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\default_post.prf \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\qml_debug.prf \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\precompile_header.prf \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\warn_on.prf \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\permissions.prf \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\qt.prf \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\resources_functions.prf \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\resources.prf \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\moc.prf \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\win32\opengl.prf \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\uic.prf \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\qmake_use.prf \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\file_copies.prf \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\win32\windows.prf \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\testcase_targets.prf \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\exceptions.prf \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\yacc.prf \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\lex.prf \
		MutiCamApp.pro \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\lib\Qt6Widgets.prl \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\lib\Qt6Gui.prl \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\lib\Qt6Core.prl \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\lib\Qt6EntryPoint.prl \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\build_pass.prf \
		Settings\settings.qrc \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\lib\Qt6Widgetsd.prl \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\lib\Qt6Guid.prl \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\lib\Qt6Cored.prl \
		..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\lib\Qt6EntryPointd.prl
	$(QMAKE) -o Makefile MutiCamApp.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\spec_pre.prf:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\common\windows-desktop.conf:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\win32\windows_vulkan_sdk.prf:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\common\windows-vulkan.conf:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\common\msvc-desktop.conf:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\qconfig.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_ext_freetype.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_ext_libjpeg.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_ext_libpng.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_ext_openxr_loader.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3danimation.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3danimation_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dcore.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dcore_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dextras.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dextras_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dinput.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dinput_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dlogic.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dlogic_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dquick.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dquick_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dquickanimation.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dquickextras.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dquickextras_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dquickinput.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dquickinput_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dquickrender.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dquickrender_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dquickscene2d.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dquickscene3d.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3dquickscene3d_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3drender.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_3drender_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_activeqt.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_activeqt_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_axbase_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_axcontainer.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_axcontainer_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_axserver.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_axserver_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_bluetooth.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_bluetooth_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_bodymovin_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_charts.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_charts_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_chartsqml.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_chartsqml_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_concurrent.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_concurrent_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_core.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_core5compat.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_core5compat_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_core_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_datavisualization.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_datavisualization_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_datavisualizationqml.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_datavisualizationqml_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_dbus.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_dbus_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_designer.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_designer_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_designercomponents_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_entrypoint_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_example_icons_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_examples_asset_downloader_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_fb_support_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_freetype_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_graphs.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_graphs_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_graphswidgets.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_graphswidgets_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_grpc.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_grpc_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_grpcquick.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_grpcquick_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_gui.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_gui_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_harfbuzz_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_help.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_help_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_httpserver.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_httpserver_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_jpeg_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_jsonrpc_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_labsanimation.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_labsanimation_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_labsfolderlistmodel.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_labsfolderlistmodel_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_labsplatform.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_labsplatform_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_labsqmlmodels.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_labsqmlmodels_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_labssettings.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_labssettings_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_labssharedimage.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_labssharedimage_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_labswavefrontmesh.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_labswavefrontmesh_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_languageserver_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_linguist.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_location.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_location_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_multimedia.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_multimedia_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_multimediaquick_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_multimediatestlibprivate_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_multimediawidgets.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_network.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_network_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_networkauth.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_networkauth_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_nfc.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_nfc_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_opengl.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_opengl_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_openglwidgets.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_openglwidgets_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_packetprotocol_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_png_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_positioning.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_positioning_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_positioningquick.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_positioningquick_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_printsupport.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_printsupport_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_protobuf.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_protobuf_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_protobufqtcoretypes.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_protobufqtcoretypes_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_protobufqtguitypes.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_protobufqtguitypes_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_protobufquick.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_protobufquick_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_protobufwellknowntypes.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_protobufwellknowntypes_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qdoccatch_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qdoccatchconversions_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qdoccatchgenerators_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qml.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qml_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmlassetdownloader.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmlassetdownloader_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmlcompiler.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmlcompiler_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmlcore.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmlcore_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmldebug_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmldom_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmlintegration.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmlintegration_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmllocalstorage.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmllocalstorage_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmlls_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmlmeta.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmlmeta_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmlmodels.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmlmodels_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmlnetwork.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmlnetwork_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmltest.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmltest_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmltoolingsettings_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmltyperegistrar_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmlworkerscript.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmlworkerscript_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmlxmllistmodel.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_qmlxmllistmodel_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3d.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3d_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dassetimport.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dassetimport_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dassetutils.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dassetutils_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3deffects.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3deffects_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dglslparser_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dhelpers.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dhelpers_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dhelpersimpl.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dhelpersimpl_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3diblbaker.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3diblbaker_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dparticleeffects.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dparticleeffects_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dparticles.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dparticles_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dphysics.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dphysics_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dphysicshelpers.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dphysicshelpers_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3druntimerender.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3druntimerender_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dspatialaudio_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dutils.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dutils_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dxr.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick3dxr_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quick_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2basic.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2basic_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2basicstyleimpl.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2basicstyleimpl_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fluentwinui3styleimpl.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fusion.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fusion_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fusionstyleimpl.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2fusionstyleimpl_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2imagine.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2imagine_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2imaginestyleimpl.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2imaginestyleimpl_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2impl.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2impl_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2material.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2material_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2materialstyleimpl.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2materialstyleimpl_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2universal.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2universal_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2universalstyleimpl.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2universalstyleimpl_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2windowsstyleimpl.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrols2windowsstyleimpl_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickcontrolstestutilsprivate_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2utils.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickdialogs2utils_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickeffects_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quicklayouts.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quicklayouts_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickparticles_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickshapes_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quicktemplates2.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quicktestutilsprivate_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quicktimeline.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quicktimeline_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quicktimelineblendtrees.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quicktimelineblendtrees_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickvectorimage.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickvectorimage_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickvectorimagegenerator_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickwidgets.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_quickwidgets_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_remoteobjects.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_remoteobjects_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_remoteobjectsqml.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_remoteobjectsqml_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_repparser.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_repparser_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_scxml.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_scxml_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_scxmlqml.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_scxmlqml_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_sensors.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_sensors_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_sensorsquick.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_sensorsquick_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_serialbus.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_serialbus_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_serialport.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_serialport_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_shadertools.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_shadertools_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_spatialaudio.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_spatialaudio_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_sql.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_sql_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_statemachine.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_statemachine_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_statemachineqml.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_statemachineqml_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_svg.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_svg_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_svgwidgets.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_svgwidgets_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_testlib.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_testlib_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_texttospeech.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_texttospeech_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_tools_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_uiplugin.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_uitools.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_uitools_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_virtualkeyboard.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_virtualkeyboard_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_virtualkeyboardsettings.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_virtualkeyboardsettings_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_webchannel.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_webchannel_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_webchannelquick.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_webchannelquick_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_websockets.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_websockets_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_webview.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_webview_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_webviewquick.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_webviewquick_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_widgets.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_widgets_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_xml.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_xml_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\modules\qt_lib_zlib_private.pri:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\qt_functions.prf:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\qt_config.prf:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\win32-msvc\qmake.conf:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\spec_post.prf:
.qmake.stash:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\exclusive_builds.prf:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\common\msvc-version.conf:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\toolchain.prf:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\default_pre.prf:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\win32\default_pre.prf:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\resolve_config.prf:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\exclusive_builds_post.prf:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\default_post.prf:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\qml_debug.prf:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\precompile_header.prf:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\warn_on.prf:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\permissions.prf:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\qt.prf:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\resources_functions.prf:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\resources.prf:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\moc.prf:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\win32\opengl.prf:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\uic.prf:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\qmake_use.prf:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\file_copies.prf:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\win32\windows.prf:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\testcase_targets.prf:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\exceptions.prf:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\yacc.prf:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\lex.prf:
MutiCamApp.pro:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\lib\Qt6Widgets.prl:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\lib\Qt6Gui.prl:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\lib\Qt6Core.prl:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\lib\Qt6EntryPoint.prl:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\mkspecs\features\build_pass.prf:
Settings\settings.qrc:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\lib\Qt6Widgetsd.prl:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\lib\Qt6Guid.prl:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\lib\Qt6Cored.prl:
..\..\..\ProgramData\Qt\6.8.2\msvc2022_64\lib\Qt6EntryPointd.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile MutiCamApp.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"

qmake_all: FORCE

make_first: debug-make_first release-make_first  FORCE
all: debug-all release-all  FORCE
clean: debug-clean release-clean  FORCE
	-$(DEL_FILE) MutiCamApp.vc.pdb
	-$(DEL_FILE) MutiCamApp.ilk
	-$(DEL_FILE) MutiCamApp.idb
distclean: debug-distclean release-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash MutiCamApp.pdb

debug-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables

check: first

benchmark: first
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
